/**
 * Which top-level groups under `docs/` the sidebar lists, and which are built without being
 * listed.
 *
 * `browsable` is what a reader of the library navigates. Each is rendered by an autogenerated
 * sidebar, so ordering and grouping inside it stay in the documents themselves.
 *
 * `unlisted` is built and linkable, deliberately absent from the navigation. `contributing/` is
 * how to work in this repository rather than how to use the library, and `decisions/` is
 * reference material the browsable pages cite thirty times — excluding either from the build
 * would turn those citations into broken links, and `onBrokenLinks: throw` would refuse the site
 * rather than quietly ship them.
 *
 * A group inside a browsable one needs no entry — `reference/generated` is carried by its
 * parent's autogenerated tree, and naming it here would also assert it exists on a tree where
 * the docs build has not run.
 *
 * `tests/sidebarCoverage.test.mjs` holds both lists against the tree, so a directory added later
 * is named in one of them rather than disappearing from the sidebar unnoticed.
 */
export const DOCS_GROUPS = {
  browsable: ["concepts", "reference"],
  unlisted: ["contributing", "decisions", "media"],
} as const;
