import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import { DOCS_GROUPS } from "./docsGroups.constants";

// One autogenerated sidebar per browsable group rather than one over the whole content root:
// ordering and grouping still stay in the documents, and the groups a reader of the library
// does not browse are built without being navigated to. Which is which lives in
// `docsGroups.constants.ts`, where a test can read it.
const sidebars: SidebarsConfig = {
  docs: [
    { type: "doc", id: "README", label: "Documentation" },
    ...DOCS_GROUPS.browsable.map((dirName) => ({ type: "autogenerated" as const, dirName })),
  ],
};

export default sidebars;
