// Every top-level group under `docs/` is either browsed or deliberately unlisted.
//
// The sidebar was one autogenerated tree over the whole content root, which had the property
// that it could not drift: whatever `docs/` held, the sidebar showed. Listing groups explicitly
// buys the ability to build a document without navigating to it, and gives that property up —
// a directory added later would simply not appear, and nothing about the site would look wrong.
//
// So the two lists are held against the tree instead. A new group fails here until it is named
// in one of them, which is the same guarantee stated once rather than inferred from a glob.

import { readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { DOCS_GROUPS } from "../apps/docs/docsGroups.constants";
import { REPO_ROOT } from "./support/repoRoot.mjs";

/** Directories a reader could be shown, relative to `docs/`, one level deep plus `reference/*`. */
function groupsOnDisk(root) {
  const docs = join(root, "docs");
  const top = readdirSync(docs, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
  const nested = top.flatMap((name) =>
    readdirSync(join(docs, name), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => `${name}/${entry.name}`),
  );
  return [...top, ...nested];
}

describe("the sidebar's group lists", () => {
  const declared = new Set([...DOCS_GROUPS.browsable, ...DOCS_GROUPS.unlisted]);

  it("names something", () => {
    expect(DOCS_GROUPS.browsable.length).toBeGreaterThan(0);
    expect(DOCS_GROUPS.unlisted.length).toBeGreaterThan(0);
  });

  it("puts no group in both lists", () => {
    const both = DOCS_GROUPS.browsable.filter((name) => DOCS_GROUPS.unlisted.includes(name));
    expect(both).toEqual([]);
  });

  it("accounts for every group on disk", () => {
    const onDisk = groupsOnDisk(REPO_ROOT);
    expect(onDisk.length).toBeGreaterThan(3);
    // A group inside a browsable one is carried by its parent's autogenerated tree.
    const unaccounted = onDisk.filter(
      (name) => !declared.has(name) && !DOCS_GROUPS.browsable.includes(name.split("/")[0] ?? name),
    );
    expect(unaccounted).toEqual([]);
  });

  it("names no group that is not there", () => {
    const onDisk = new Set(groupsOnDisk(REPO_ROOT));
    expect([...declared].filter((name) => !onDisk.has(name))).toEqual([]);
  });
});
