import { expect, test } from "vitest";

test("exports exactly the optional UI contract", async () => {
  expect(Object.keys(await import("./index")).sort()).toEqual([
    "BlockPalette",
    "BoundedTextField",
    "ConsumerOriginContext",
    "FieldsWithCallout",
    "FieldsetGroup",
    "IssuesPill",
    "LinkTextField",
    "OutcomeNotice",
    "PaletteIcon",
    "PublishControl",
    "PuckApiBridge",
    "ReadOnlyField",
    "RepeaterField",
    "RichTextField",
    "RouteSwitcher",
    "SEGMENTED_MAX_MEMBERS",
    "ScalarFieldControl",
    "SegmentedEnumField",
    "StudioEditor",
    "StudioOutline",
    "StudioStatusBar",
    "StudioToolbar",
    "SubFieldControl",
    "ToolbarDocument",
    "directChildFields",
    "focusIssueField",
    "isLinkField",
    "isRichTextField",
    "leafFieldName",
    "puckAdapter",
    "richTextFieldNodes",
    "rowFieldOf",
    "selectPuckNode",
    "toHintedFields",
    "useCloseOnEscape",
    "useCloseOnOutsideClick",
    "useDraftSave",
    "useEditorStatus",
  ]);
});
